name: skywise
description: "A premium weather application."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.2
  http: ^1.2.1
  geolocator: ^12.0.0
  intl: ^0.19.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  url_launcher: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  # The broken package has been REMOVED

flutter:
  uses-material-design: true
  assets:
    - assets/

# The configuration for the broken package has been REMOVED

